#### general settings
name: highlight_generation
model: hallucination_GAN
use_tb_logger: true
distortion: sr
scale: 1
gpu_ids: [0]

#### datasets
datasets:
  train:
    name: HDRTV1K
    mode: LQGT_hallucination
    dataroot_LQ: ../dataset/training_set/LE_training_set_res_sub
    dataroot_GT: ../dataset/training_set/train_hdr_sub
    dataroot_mask: ../dataset/training_set/train_sdr_sub_mask
    use_shuffle: true
    n_workers: 8
    batch_size: 16
    GT_size: 128
    use_flip: false
    use_rot: false
  val:
    name: HDRTV1K
    mode: LQGT_hallucination
    dataroot_LQ: ../dataset/test_set/LE_test_set_res_bicx4 # downsampling for fast validation
    dataroot_GT: ../dataset/test_set/test_hdr_bicx4 # downsampling for fast validation
    dataroot_mask: ../dataset/test_set/test_sdr_bicx4_mask
    save_img: false

#### network structures
network_G:
  which_model_G: Hallucination_Generator 
  in_nc: 3
  out_nc: 3
  nf: 64
  residual: true

network_D:
  which_model_D: discriminator_vgg_128
  in_nc: 3
  nf: 64

#### path
path:
  root: ./
  pretrain_model_G: ../experiments/highlight_generation_pretrain/models/latest_G.pth
  strict_load: true
  # resume_state: ../experiments/...

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 1e-4
  weight_decay_G: 0
  beta1_G: 0.9
  beta2_G: 0.99
  lr_D: !!float 1e-4
  weight_decay_D: 0
  beta1_D: 0.9
  beta2_D: 0.99
  lr_scheme: MultiStepLR

  niter: 400000
  warmup_iter: -1  # no warm up
  lr_steps: [50000, 100000, 200000, 300000]
  lr_gamma: 0.5

  pixel_criterion: l1
  pixel_weight: !!float 1e-2
  feature_criterion: l1
  feature_weight: 1
  gan_type: gan  # gan | ragan
  gan_weight: !!float 5e-3

  TVloss_weight: 0 # !!float 1e-1

  D_update_ratio: 1
  D_init_iters: 0

  manual_seed: 10
  val_freq: !!float 5e3

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
